<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BooksTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('books')->insert([
            [
                'title' => 'The Hunger Games',
                'author' => 'Suzanne Collins',
                'genre' => 'Action, Sci-fi, Fantasy',
                'description' => 'Could you survive on your own in the wild, with every one out to make sure you don\'t live to see the morning? In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and one girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV. Sixteen-year-old Katniss Everdeen, who lives alone with her mother and younger sister, regards it as a death sentence when she steps forward to take her sister\'s place in the Games. But Katniss has been close to dead before—and survival, for her, is second nature. Without really meaning to, she becomes a contender. But if she is to win, she will have to start making choices that weight survival against humanity and life against love.',
                'cover' => 'assets\\covers\\The Hunger Games.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Catching Fire',
                'author' => 'Suzanne Collins',
                'genre' => 'Action, Sci-fi, Fantasy, Romance',
                'description' => 'Sparks are igniting. Flames are spreading. And the Capitol wants revenge. Against all odds, Katniss Everdeen has won the Hunger Games. She and fellow District 12 tribute Peeta Mellark are miraculously still alive. Katniss should be relieved, happy even. After all, she has returned to her family and her longtime friend, Gale. Yet nothing is the way Katniss wishes it to be. Gale holds her at an icy distance. Peeta has turned his back on her completely. And there are whispers of a rebellion against the Capitol—a rebellion that Katniss and Peeta may have helped create. Much to her shock, Katniss has fueled an unrest that she\'s afraid she cannot stop. And what scares her even more is that she\'s not entirely convinced she should try. As time draws near for Katniss and Peeta to visit the districts on the Capitol\'s cruel Victory Tour, the stakes are higher than ever. If they can\'t prove, without a shadow of a doubt, that they are lost in their love for each other, the consequences will be horrifying.',
                'cover' => 'assets\\covers\\Catching Fire.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Mockingjay',
                'author' => 'Suzanne Collins',
                'genre' => 'Action, Sci-fi, Fantasy, Adventure, Fiction, Romance',
                'description' => 'My name is Katniss Everdeen. Why am I not dead? I should be dead. Katniss Everdeen, girl on fire, has survived, even though her home has been destroyed. Gale has escaped. Katniss\'s family is safe. Peeta has been captured by the Capitol. District 13 really does exist. There are rebels. There are new leaders. A revolution is unfolding. It is by design that Katniss was rescued from the arena in the cruel and haunting Quarter Quell, and it is by design that she has long been part of the revolution without knowing it. District 13 has come out of the shadows and is plotting to overthrow the Capitol. Everyone, it seems, has had a hand in the carefully laid plans—except Katniss. The success of the rebellion hinges on Katniss\'s willingness to be a pawn, to accept responsibility for countless lives, and to change the course of the future of Panem. To do this, she must put aside her feelings of anger and distrust. She must become the rebels\' Mockingjay—no matter what the personal cost.',
                'cover' => 'assets\\covers\\Mockingjay.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Divergent',
                'author' => 'Veronica Roth',
                'genre' => 'Action, Fiction, Fantasy, Sci-Fi, Romance',
                'description' => 'In Beatrice Prior\'s dystopian Chicago world, society is divided into five factions, each dedicated to the cultivation of a particular virtue—Candor (the honest), Abnegation (the selfless), Dauntless (the brave), Amity (the peaceful), and Erudite (the intelligent). On an appointed day of every year, all sixteen-year-olds must select the faction to which they will devote the rest of their lives. For Beatrice, the decision is between staying with her family and being who she really is—she can\'t have both. So she makes a choice that surprises everyone, including herself. During the highly competitive initiation that follows, Beatrice renames herself Tris and struggles alongside her fellow initiates to live out the choice they have made. Together they must undergo extreme physical tests of endurance and intense psychological simulations, some with devastating consequences. As initiation transforms them all, Tris must determine who her friends really are—and where, exactly, a romance with a sometimes fascinating, sometimes exasperating boy fits into the life she\'s chosen. But Tris also has a secret, one she\'s kept hidden from everyone because she\'s been warned it can mean death. And as she discovers unrest and growing conflict that threaten to unravel her seemingly perfect society, she also learns that her secret might help her save those she loves . . . or it might destroy her.',
                'cover' => 'assets\\covers\\Divergent.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Insurgent',
                'author' => 'Veronica Roth',
                'genre' => 'Action, Fiction, Fantasy, Sci-Fi, Romance',
                'description' => "One choice can transform you—or it can destroy you. But every choice has consequences, and as unrest surges in the factions all around her, Tris Prior must continue trying to save those she loves—and herself—while grappling with haunting questions of grief and forgiveness, identity and loyalty, politics and love.\r\n\r\nTris's initiation day should have been marked by celebration and victory with her chosen faction; instead, the day ended with unspeakable horrors. War now looms as conflict between the factions and their ideologies grows. And in times of war, sides must be chosen, secrets will emerge, and choices will become even more irrevocable—and even more powerful. Transformed by her own decisions but also by haunting grief and guilt, radical new discoveries, and shifting relationships, Tris must fully embrace her Divergence, even if she does not know what she may lose by doing so.\r\n\r\nNew York Times bestselling author Veronica Roth's much-anticipated second book of the dystopian DIVERGENT series is another intoxicating thrill ride of a story, rich with hallmark twists, heartbreaks, romance, and powerful insights about human nature.",
                'cover' => 'assets\\covers\\Insurgent.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Allegiant',
                'author' => 'Veronica Roth',
                'genre' => 'Action, Fiction, Fantasy, Sci-Fi, Romance',
                'description' => "The faction-based society that Tris Prior once believed in is shattered - fractured by violence and power struggles and scarred by loss and betrayal. So when offered a chance to explore the world past the limits she's known, Tris is ready. Perhaps beyond the fence, she and Tobias will find a simple new life together, free from complicated lies, tangled loyalties, and painful memories.\r\n\r\nBut Tris's new reality is even more alarming than the one she left behind. Old discoveries are quickly rendered meaningless. Explosive new truths change the hearts of those she loves. And once again, Tris must battle to comprehend the complexities of human nature - and of herself - while facing impossible choices about courage, allegiance, sacrifice, and love.\r\n\r\nTold from a riveting dual perspective, ALLEGIANT, by #1 New York Times best-selling author Veronica Roth, brings the DIVERGENT series to a powerful conclusion while revealing the secrets of the dystopian world that has captivated millions of readers in DIVERGENT and INSURGENT.",
                'cover' => 'assets\\covers\\Allegiant.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Maze Runner',
                'author' => 'James Dashner',
                'genre' => 'Action, Fiction, Fantasy, Sci-Fi, Thriller',
                'description' => "If you ain’t scared, you ain’t human.\r\n\r\nWhen Thomas wakes up in the lift, the only thing he can remember is his name. He’s surrounded by strangers—boys whose memories are also gone.\r\n\r\nNice to meet ya, shank. Welcome to the Glade.\r\n\r\nOutside the towering stone walls that surround the Glade is a limitless, ever-changing maze. It’s the only way out—and no one’s ever made it through alive.\r\n\r\nEverything is going to change.\r\n\r\nThen a girl arrives. The first girl ever. And the message she delivers is terrifying.\r\n\r\nRemember. Survive. Run.",
                'cover' => 'assets\\covers\\The Maze Runner.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Maze Runner: The Scorch Trials',
                'author' => 'James Dashner',
                'genre' => 'Action, Fiction, Fantasy, Sci-Fi, Thriller',
                'description' => '',
                'cover' => 'assets\covers\Scorch Trials.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Maze Runner: The Death Cure',
                'author' => 'James Dashner',
                'genre' => 'Action, Fiction, Fantasy, Sci-Fi, Thriller',
                'description' => 'An all new, original Maze Runner story set directly before the upcoming third film, The Death Cure.  
                    They used to live and die by the Maze—a seemingly endless labyrinth of deathtraps that kept the Gladers prisoner and in fear. But the day Thomas arrived, he motivated them all to push back...and escape. 
                    But what they discovered was far worse than any maze—a world scorched by disease and controlled by the oppressive organization, Wicked. Thomas, Aided by a band of rebels, now readies to take the fight right to Wicked’s doorstep in the hope of finding a cure for the plague that’s ravaging mankind.
                    This all-new, authorized graphic novel bridges the gap between the second and third installments (Scorch Trials, The Death Cure) of the hit film franchise, The Maze Runner.',
                'cover' => 'assets\\covers\\Death Cure.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Lightning Thief',
                'author' => 'Rick Riordan',
                'genre' => 'Action, Adventure, Fantasy, Fiction',
                'description' => "Percy Jackson is a good kid, but he can't seem to focus on his schoolwork or control his temper. And lately, being away at boarding school is only getting worse - Percy could have sworn his pre-algebra teacher turned into a monster and tried to kill him. When Percy's mom finds out, she knows it's time that he knew the truth about where he came from, and that he go to the one place he'll be safe. She sends Percy to Camp Half Blood, a summer camp for demigods (on Long Island), where he learns that the father he never knew is Poseidon, God of the Sea. Soon a mystery unfolds and together with his friends—one a satyr and the other the demigod daughter of Athena - Percy sets out on a quest across the United States to reach the gates of the Underworld (located in a recording studio in Hollywood) and prevent a catastrophic war between the gods.",
                'cover' => 'assets\\covers\\The Lightning Thief.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Heist Royale',
                'author' => 'Kayvion Lewi',
                'genre' => 'Action, Mystery, Thriller, Fiction, Romance, Fantasy, Adventure',
                'description' => "The high-stakes sequel to Thieves' Gambit, for fans of Jennifer Lynn Barnes and Ally Carter.
                    It's been six months since the end of the Gambit. Instead of winning an impossible wish, Ross has the threat of her family’s execution hanging over her head. Devroe, the only person Ross thought she could trust, could wish the Quests into oblivion at any time. Shockingly, despite his betrayal, Devroe is still making a play for Ross’s heart as the two work together pulling jobs for the Organization. But Ross has learned her lesson: A Quest can only trust another Quest.
                    When Ross finds herself at the center of a power struggle within the Organization, she sees her chance to change her fortunes. As a new deadly Gambit develops for control of the criminal underworld, Ross strikes a risky deal to guarantee protection for herself and her family.
                    In this final clash, Ross will square off against a ruthless opponent who will stop at nothing to seize power, and in their corner will be not only Devroe but his mother, who wants to destroy the Quests at any cost.
                    The new Gambit takes Ross and her crew into the intoxicating casinos of Monte Carlo and across treacherous snow-covered slopes in Antarctica as Ross competes against Devroe in a fight for her life. Loyalties will be tested, backs stabbed, hearts broken. May the best thief win.",
                'cover' => 'assets\covers\Heist Royale.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Killing Floor',
                'author' => 'Lee Child',
                'genre' => 'Action, Mystery, Thriller, Fiction, Romance, Fantasy, Adventure',
                'description' => "Ex-military policeman Jack Reacher is a drifter. He’s just passing through Margrave, Georgia, and in less than an hour, he’s arrested for murder. Not much of a welcome. All Reacher knows is that he didn’t kill anybody. At least not here. Not lately. But he doesn’t stand a chance of convincing anyone. Not in Margrave, Georgia. Not a chance in hell.",
                'cover' => 'assets\\covers\\Killing Floor.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Improvisers',
                'author' => 'Nicole Glover',
                'genre' => 'Adventure, Fantasy, Historical Fiction, Fiction, Mystery',
                'description' => "Velma Frye is many things. A pilot, a former bootlegger, a well-seasoned traveler, a jazz pianist…and a wielder of celestial magic. She’s also a member of the mystical Rhodes family as well as an investigator for arcane oddities for a magic rights organization, dealing with both simple and complicated cases. And when a pocket watch instigates a magical brawl after one of her flight shows, things become very complicated. 
                    In 1930s America, enchanted items are highly valuable, especially in the waning days of the magical Prohibition. As Velma digs deeper, she discovers the watch is part of a collection of dangerous artifacts manipulating people across the country—and in some cases, leading to their deaths. Something about all this is tickling Velma’s memories, and the more she discovers, the more these seemingly isolated incidents feel as if they’re building to something apocalyptic.
                    Connecting the dots isn’t easy, though, and further complicating her work is journalist Dillon Harris. He hounds her steps, and while not actively sabotaging her investigation, he also clearly knows more than he lets on. Whether it’s his presence that she finds so vexing or his easygoing charm, that’s a mystery she isn’t interested in solving. Because someone is out there seeding cursed objects with the intent on wreaking havoc, and Velma will have to use every trick in her tool kit, including some well-placed magical improvisation, to win the day. 
                    Focusing on a new generation of the Rhodes family, The Improvisers brims with charming magic, intriguing mystery, and high-flying adventure seeking new heights.",
                'cover' => 'assets\\covers\\The Improvisers.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'A Tale Told By Traitors',
                'author' => 'Renee Dugan',
                'genre' => 'Adventure, Fantasy, Romance, Fiction',
                'description' => "LIONYRA VARA is not who she seems. 
                    A humble immigrant baker living in Mithra-Sha, Lio hides a bitter truth—she is truly the sole inheritor of the ruling regime in the neighboring country of Amere-Del. And now, against her will, Lio is going back—to the land of her worst fears and lifelong nightmares. 
                    And she won’t be going alone; the life of her oldest friend hangs in the same cruel balance. Their only hope for freedom is to outwit the people who seek to enslave them to the fate they left behind. 
                    But to do it, they must first find their way back to each other. 
                    RYKER KASSIAN is a man caught between desperation and redemption. 
                    A legendary pirate swimming in insurmountable debt, Ryker sees only one way to slip the noose for himself and his beloved—by offering the runaway Delina as a ransom for a lofty sum. But when the lost heir offers him a chance at something more—by helping her hunt down her missing friend—Ryker seizes the opportunity without a second thought. It might be his only chance to fix everything he’s broken…and save his crew from slaughter. 
                    As their hunt takes them to hidden pirate cities, sinister port towns, and the treacherous heart of Amere-Del where revolution threatens to ignite, all of their secrets and schemes collide. Backed against the tenuous balance of an impending civil war, Lio and Ryker have no choice but to confront the bitter truths they’ve fled from, the causes they’ve betrayed, the schemes for their destruction…and a rising attraction they both deny. 
                    And with a ruthless regime seeking both their heads, they must choose which side of the line they stand on—whether they remain enemies divided, or become allies in the fight to shape their own destinies",
                'cover' => 'assets\\covers\\A Tale Told By Traitors.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Treasure Hunters Club',
                'author' => 'Tom Ryan',
                'genre' => 'Adventure, Mystery, Thriller, Fiction',
                'description' => "For nearly a century, people have ventured to the idyllic seaside town of Maple Bay in search of a legendary lost pirate treasure, but locals know there’s more than just gold buried in the sand. As the paths of three strangers converge in Maple Bay, the truth is about to be blown wide open. But not before the bodies start to pile up. 
                    Peter Barnett is rapidly approaching 40 with little to show for it when a mysterious letter invites him to Maple Bay and the mansion his estranged family has called home for generations. 
                    Seventeen-year-old Dandy Feltzen is isolated and adrift following the death of her beloved grandfather, until his final request and a tantalizing clue sets her on a mission to solve the mystery he spent his entire life chasing. 
                    Cass Jones has given up on her dream of being a successful author when an unexpected opportunity lands her a housesitting gig in remote Maple Bay, where she stumbles on the perfect subject matter for her breakout book—and the handsome sailor who might be just the person to help her research it. 
                    Peter, Dandy and Cass have never met, but they’re on a collision course with each other and the mystery that has defined Maple Bay for two centuries, and none of them are prepared for the shocking truths that may or may not still be buried there.",
                'cover' => 'assets\\covers\\The Treasure Hunters Club.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Dungeon Crawler Carl',
                'author' => 'Matt Dinniman',
                'genre' => 'Adventure, Fantasy, Fiction, Sci-Fi, Comedy',
                'description' => "The apocalypse will be televised!
                    A man. His ex-girlfriend's cat. A sadistic game show unlike anything in the universe: a dungeon crawl where survival depends on killing your prey in the most entertaining way possible.
                    In a flash, every human-erected construction on Earth—from Buckingham Palace to the tiniest of sheds—collapses in a heap, sinking into the ground.
                    The buildings and all the people inside have all been atomized and transformed into the dungeon: an 18-level labyrinth filled with traps, monsters, and loot. A dungeon so enormous, it circles the entire globe.
                    Only a few dare venture inside. But once you're in, you can't get out. And what's worse, each level has a time limit. You have but days to find a staircase to the next level down, or it's game over. In this game, it's not about your strength or your dexterity. It's about your followers, your views. Your clout. It's about building an audience and killing those goblins with style.
                    You can't just survive here. You gotta survive big.
                    You gotta fight with vigor, with excitement. You gotta make them stand up and cheer. And if you do have that 'it' factor, you may just find yourself with a following. That's the only way to truly survive in this game—with the help of the loot boxes dropped upon you by the generous benefactors watching from across the galaxy.
                    They call it Dungeon Crawler World. But for Carl, it's anything but a game.",
                'cover' => 'assets\\covers\\Dungeon Crawler Carl.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'He Who Fights with Monsters',
                'author' => 'Shirtaloon',
                'genre' => 'Adventure, Fantasy, Fiction, Sci-fi, Action',
                'description' => "Jason wakes up in a mysterious world of magic and monsters.
                    It’s not easy making the career jump from office-supplies-store middle manager to heroic interdimensional adventurer. At least, Jason tries to be heroic, but it's hard to be good when all your powers are evil.
                    He’ll face off against cannibals, cultists, wizards, monsters...and that’s just on the first day. He’s going to need courage, he’s going to need wit, and he’s going to need some magic powers of his own. But first, he’s going to need pants.",
                'cover' => 'assets\\covers\\He Who Fights with Monsters.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Eye of the Bedlam Bride',
                'author' => 'Matt Dinniman',
                'genre' => 'Adventure, Fantasy, Fiction, Sci-fi, Comedy',
                'description' => "A pantheon of forgotten gods. An old grudge between a talk show host, an heiress, and the man they shattered along the way. A rapidly deteriorating AI system. An inconvenient tiara upon the head of a friend.
                    It is bedlam on the eighth floor.  
                    As management reels from the unexpected conclusion of the seventh level, the surviving crawlers stumble onto the eighth and find themselves scattered. It’s a map based on Earth’s final days before the collapse, where ethereal, intangible ghosts of humanity go about their lives, oblivious of the impending doom. Living amongst these ghosts are monsters based in Earth lore. “Legendary” creatures tied to the geographical location they inhabit.
                    Each team of crawlers is given a task: find and capture six of these beasts. The captured monsters will be turned into cards. Cards that can be summoned into battle again and again. The stronger, the deadlier, the better.
                    At the end of the floor, the bad guys will also have decks, and they will have some of the most powerful cards available. So it’s crucial to assemble the toughest squad possible.
                    But, like always, there is a catch. There’s always a catch.
                    As Carl and Donut know all too well, just because someone is captured, it doesn’t mean they have been tamed.
                    Her name is Shi Maria. She’s easily the most powerful monster in their area. If they want to survive, they must capture her. But she is no ordinary beast. She’s intelligent. She was once married to a god, a god who is now missing. Her special attack is known to drive one insane. They call her the Bedlam Bride.
                    “Beware, beware. Beware the Eye of the Bedlam Bride”.",
                'cover' => 'assets\\covers\\The Eye of the Bedlam Bride.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Summit’s Edge',
                'author' => 'Sara Driscoll',
                'genre' => 'Adventure, Mystery, Thriller, Action',
                'description' => "FBI handler Meg Jennings and her K-9 partner, Hawk, vie to rescue plane crash survivors from a Colorado mountain—and contend with a hijacker determined to stop them.
                    As long as there’s hope of finding life, no mission is too dangerous for Meg Jennings and her colleagues in the FBI K-9 unit. But locating the wreckage of a hijacked private plane high in the Elk Mountains of Colorado is treacherous in a multitude of ways—some of them impossible for even a seasoned team to predict.
                    The plane, carrying the board of directors of Barron Pharmaceuticals, crashed on a rocky peak and was cleaved in two. Perilous weather means the rescuers have to ascend on foot, with their dogs unleashed in case of falls. It takes hours to locate the wreckage, but miraculously, Meg and Hawk find half a dozen passengers and crew still alive. The hijacker also survived and has fled into the wilderness with the CEO’s son in pursuit.
                    As soon as day breaks, the K-9 teams set out to find both men, and the dogs quickly pick up a scent trail. Meg has used her connections with an investigative reporter to learn as much as she can about the hijacker, hoping to use it when they apprehend him. But first, they must contend with the mountain’s savage fury, and an adversary who will destroy as many lives as possible rather than face justice.",
                'cover' => 'assets\\covers\\Summits Edge.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Harry Potter and the Sorcerer’s Stone',
                'author' => 'J.K. Rowling',
                'genre' => 'Children’s, Adventure, Sci-fi, Fantasy',
                'description' => "Turning the envelope over, his hand trembling, Harry saw a purple wax seal bearing a coat of arms; a lion, an eagle, a badger and a snake surrounding a large letter 'H'.
                    Harry Potter has never even heard of Hogwarts when the letters start dropping on the doormat at number four, Privet Drive. Addressed in green ink on yellowish parchment with a purple seal, they are swiftly confiscated by his grisly aunt and uncle. Then, on Harry's eleventh birthday, a great beetle-eyed giant of a man called Rubeus Hagrid bursts in with some astonishing news: Harry Potter is a wizard, and he has a place at Hogwarts School of Witchcraft and Wizardry. An incredible adventure is about to begin!",
                'cover' => 'assets\\covers\\Harry Potter and the Sorcerers Stone.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Lotus Empire',
                'author' => 'Tasha Suri',
                'genre' => 'Fantasy, LGBTQ+, Romance, Fiction',
                'description' => "Malini has claimed her rightful throne as the empress of Parijatdvipa, just as the nameless gods prophesied. Now, in order to gain the support of the priesthood who remain loyal to the fallen emperor, she must consider a terrible Claim her throne and burn in order to seal her legacy—or find another willing to take her place on the pyre.
                    Priya has survived the deathless waters and now their magic runs in her veins. But a mysterious yaksa with flowering eyes and a mouth of thorns lies beneath the waters. The yaksa promises protection for Ahiranya. But in exchange, she needs a sacrifice. And she's chosen Priya as the one to offer it.
                    Two women once entwined by fate now stand against each other. But when an ancient enemy rises to threaten their world, Priya and Malini will find themselves fighting together once more – to prevent their kingdoms, and their futures, from burning to ash.",
                'cover' => 'assets\\covers\\The Lotus Empire.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'A Wild and Ruined Song',
                'author' => 'Ashley Shuttleworth',
                'genre' => 'Fantasy, LGBTQ+, Romance',
                'description' => "Arlo and her friends struggle to rally against an overwhelming foe before time runs out in this gripping final book in the Hollow Star Saga, the urban fantasy series about fae in Toronto.
                    Arlo Jarsdel has lost everything. Her family. Her freedom. Her name. And now that she’s sharing her body with Ruin, the formidable titan of devastation, she’s even beginning to lose herself.
                    In their most dangerous game of deception yet, Arlo has just one goal: destroy the three Bone Crowns corrupting the mortal and immortal realms before her time runs out and Ruin takes permanent control of her being.
                    With Celadon fighting on the political front against the ruthless High Queen Riadne—now armed with the cataclysmic power of her Crown, the Sins, and Ruin—Vehan and Aurelian are scrambling in secret to build an army to rival Riadne’s infernal forces. Meanwhile, Nausicaä will do whatever it takes to save her girlfriend from obliteration, despite knowing the odds of survival are nearly nonexistent.
                    When the line between hero and villain becomes blurred, and bonds are put to the ultimate test, it has never been more imperative—or more difficult—to stand united. For this is not the first lifetime that these five friends have faced the evil behind this impending war, but if they can’t find their way back to each other, it might just be their last.",
                'cover' => 'assets\\covers\\A Wild and Ruined Song.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Hitchhiker’s Guide to the Galaxy',
                'author' => 'Douglas Adams',
                'genre' => 'Comedy, Sci-Fi',
                'description' => "Arthur Dent is having a bad day. His house is about to be demolished, he learns that his best friend is an alien, and Earth is about to be destroyed to make way for a hyperspace bypass. Together, they embark on an intergalactic journey filled with absurdity, hilarity, and the answer to life, the universe, and everything.",
                'cover' => 'assets\\covers\\The Hitchhikers Guide to the Galaxy.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Good Omens',
                'author' => 'Neil Gaiman and Terry Pratchett',
                'genre' => 'Comedy, Fantasy',
                'description' => "A demon and an angel team up to stop Armageddon, but things get complicated when they misplace the Antichrist. This irreverent and witty take on the apocalypse is filled with quirky characters and laugh-out-loud moments.",
                'cover' => 'assets\\covers\\Good Omens.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Me Talk Pretty One Day',
                'author' => 'David Sedaris',
                'genre' => 'Comedy, Memoir',
                'description' => "A collection of essays blending humor and heart, David Sedaris reflects on his life, family, and misadventures, from his childhood to his struggles with learning French in Paris.",
                'cover' => 'assets\\covers\\Me Talk Pretty One Day.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Bossypants', 
                'author' => 'Tina Fey',
                'genre' => 'Comedy, Memoir',
                'description' => "Tina Fey shares her journey from awkward teenager to comedy superstar in this hilarious memoir, filled with laugh-out-loud anecdotes and thoughtful insights about life and the entertainment industry.",
                'cover' => 'assets\\covers\\Bossypants.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Let’s Pretend This Never Happened',
                'author' => 'Jenny Lawson',
                'genre' => 'Comedy, Memoir',
                'description' => "Lawson recounts her bizarre and hilarious life experiences, from taxidermy-obsessed parents to her eccentric adulthood, with unfiltered humor and heartwarming honesty.",
                'cover' => 'assets\\covers\\Lets Pretend This Never Happened.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Hyperbole and a Half',
                'author' => 'Allie Brosh',
                'genre' => 'Comedy, Graphic Novel',
                'description' => "Based on her popular blog, Brosh's book combines absurdly funny and brutally honest illustrated stories about her childhood, her dogs, and her struggles with depression.",
                'cover' => 'assets\\covers\\Hyperbole and a Half.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'A Confederacy of Dunces',
                'author' => 'John Kennedy Toole',
                'genre' => 'Comedy, Fiction',
                'description' => "Ignatius J. Reilly is a lazy, eccentric man living in New Orleans who becomes entangled in a series of ridiculous adventures. This Pulitzer Prize-winning novel is a comedic masterpiece.",
                'cover' => 'assets\\covers\\A Confederacy of Dunces.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Catch-22',
                'author' => 'Joseph Heller',
                'genre' => 'Comedy, Fiction',
                'description' => "A darkly comedic take on the absurdities of war, this novel follows Captain John Yossarian as he tries to maintain his sanity in a bureaucratic military system that defies logic.",
                'cover' => 'assets\\covers\\Catch-22.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Three Men in a Boat',
                'author' => 'Jerome K. Jerome',
                'genre' => 'Comedy, Classic',
                'description' => "A classic British comedy about three friends and their dog on a river trip along the Thames, filled with humorous mishaps and amusing observations about life.",
                'cover' => 'assets\\covers\\Three Men in a Boat.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Code of the Woosters',
                'author' => 'P.G. Wodehouse',
                'genre' => 'Comedy, Fiction',
                'description' => "Bertie Wooster and his resourceful butler Jeeves get caught up in a tangle of engagements, stolen artifacts, and eccentric aristocrats in this charming and hilarious novel.",
                'cover' => 'assets\\covers\\The Code of the Woosters.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Name of the Wind',
                'author' => 'Patrick Rothfuss',
                'genre' => 'Fantasy, Adventure, Fiction',
                'description' => "Kvothe, a gifted young man, recounts his life story in this epic tale of adventure, magic, and music. From humble beginnings as an orphan to becoming the most legendary figure in his world, Kvothe seeks to learn the truth behind the mysterious death of his parents. Along the way, he finds love, betrayal, and confronts powerful enemies.",
                'cover' => 'assets\\covers\\The Name of the Wind.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Mistborn: The Final Empire',
                'author' => 'Brandon Sanderson',
                'genre' => 'Fantasy, Adventure, Fiction',
                'description' => "In a world where ash falls from the sky and mist dominates the night, a rebellion is brewing. The oppressed 'skaa' class is ruled by the immortal Lord Ruler. Vin, a young orphan girl, discovers that she possesses an extraordinary power—Allomancy, the ability to manipulate metals. She joins a crew of rebels planning to overthrow the Lord Ruler, uncovering secrets that could change the world.",
                'cover' => 'assets\\covers\\Mistborn The Final Empire.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Way of Kings',
                'author' => 'Brandon Sanderson',
                'genre' => 'Fantasy, Adventure, Fiction',
                'description' => "On the storm-battered world of Roshar, humans struggle to survive against constant wars, highstorms, and strange creatures. Dalinar Kholin, a warlord, is haunted by visions that speak of a forgotten past and an impending catastrophe. With the fate of the world at stake, Dalinar must unite his people and face a looming darkness that threatens to destroy everything.",
                'cover' => 'assets\\covers\\The Way of Kings.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => '',
                'author' => '',
                'genre' => '',
                'description' => "",
                'cover' => 'assets\\covers\\',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Priory of the Orange Tree',
                'author' => 'Samantha Shannon',
                'genre' => 'Fantasy, LGBTQ+, Adventure',
                'description' => "A tale of dragons, sorcery, and the fate of the world. The story is set in a world where dragons are revered, feared, and vital to the survival of humankind. As the world faces an ancient threat, the destinies of several women—including a dragon-riding queen, a dragon-riding witch, and a dragon-rider's daughter—intertwine in an epic saga that explores friendship, loyalty, and the power of dragons.",
                'cover' => 'assets\\covers\\The Priory of the Orange Tree.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Hobbit',
                'author' => 'J.R.R. Tolkien',
                'genre' => 'Fantasy, Adventure, Children’s',
                'description' => "Bilbo Baggins, a simple hobbit, is swept away on an unexpected journey to reclaim treasure from the fearsome dragon Smaug. Along the way, he encounters elves, goblins, and trolls, and discovers his courage. This prequel to The Lord of the Rings introduces the enchanting world of Middle-earth and the unlikely hero who becomes part of its greatest legends.",
                'cover' => 'assets\\covers\\The Hobbit.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'A Court of Thorns and Roses',
                'author' => 'Sarah J. Maas',
                'genre' => 'Fantasy, Romance, Fiction',
                'description' => "Feyre, a mortal girl, is taken to the land of the Fae after killing a wolf that was actually a faerie in disguise. She is brought before Tamlin, a High Fae lord, and becomes embroiled in the political intrigue and dangers of the Fae realm. As she navigates her growing feelings for Tamlin, Feyre uncovers dark secrets that could lead to a deadly war.",
                'cover' => 'assets\\covers\\A Court of Thorns and Roses.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Lies of Locke Lamora',
                'author' => 'Scott Lynch',
                'genre' => 'Fantasy, Adventure, Crime, Fiction',
                'description' => "In the city of Camorr, a place full of criminals and dangerous secrets, Locke Lamora leads a group of thieves known as the Gentlemen Bastards. Using wit, charm, and a talent for deception, Locke navigates the dangerous world of thieves and nobles. But when a new, powerful enemy appears, Locke must use all his cunning to survive and protect his friends.",
                'cover' => 'assets\\covers\\The Lies of Locke Lamora.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Black Prism',
                'author' => 'Brent Weeks',
                'genre' => 'Fantasy, Adventure, Fiction',
                'description' => "In a world where magic is controlled by the manipulation of light, Gavin Guile is the most powerful man alive—the Prism. But when Gavin’s younger brother, Kip, discovers he has magical powers that could destroy the world, he must choose between family loyalty and the fate of the world. The story is filled with complex characters, political intrigue, and epic battles.",
                'cover' => 'assets\\covers\\The Black Prism.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Bone Shard Daughter',
                'author' => 'Andrea Stewart',
                'genre' => 'Fantasy, Adventure, Fiction',
                'description' => "In a land where the emperor controls magic through bone shard magic, Lin, the emperor’s daughter, seeks to prove herself worthy of the throne by mastering this ancient power. As she uncovers dark secrets about the empire and the power her father holds, Lin must decide who to trust and what she’s willing to sacrifice to save her people.",
                'cover' => 'assets\\covers\\The Bone Shard Daughter.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The City of Brass',
                'author' => 'S.A. Chakraborty',
                'genre' => 'Fantasy, Historical Fiction, Adventure',
                'description' => "In 18th-century Cairo, Nahri, a street-smart con woman, accidentally summons a powerful djinn named Dara. This event sets off a chain of events that leads Nahri into the heart of the magical city of Daevabad, where politics, magic, and ancient powers collide. As she becomes embroiled in a war between djinn factions, Nahri discovers secrets about her own mysterious origins.",
                'cover' => 'assets\\covers\\The City of Brass.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Great Gatsby',
                'author' => 'F. Scott Fitzgerald',
                'genre' => 'Fiction, Classic, Romance',
                'description' => "The Great Gatsby follows Jay Gatsby, a wealthy and mysterious businessman who hosts extravagant parties in the hopes of rekindling a romance with his lost love, Daisy Buchanan. Through the eyes of narrator Nick Carraway, the novel explores themes of wealth, class, and the American Dream during the Roaring Twenties.",
                'cover' => 'assets\\covers\\The Great Gatsby.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'To Kill a Mockingbird',
                'author' => 'Harper Lee',
                'genre' => 'Fiction, Classic, Historical Fiction',
                'description' => "Set in the 1930s, this Pulitzer Prize-winning novel tells the story of Scout Finch, a young girl growing up in the racially segregated South. As her father, lawyer Atticus Finch, defends a black man wrongly accused of raping a white woman, Scout learns difficult lessons about prejudice, morality, and justice.",
                'cover' => 'assets\\covers\\To Kill a Mockingbird.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => '1984',
                'author' => 'George Orwell',
                'genre' => 'Fiction, Political Fiction',
                'description' => "In George Orwell’s chilling dystopian novel, 1984, Winston Smith lives in a totalitarian state under constant surveillance by the Party and its leader, Big Brother. The novel explores themes of freedom, truth, and the oppression of individuality as Winston questions the reality imposed by the regime.",
                'cover' => 'assets\\covers\\1984.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Catcher in the Rye',
                'author' => 'J.D. Salinger',
                'genre' => 'Fiction, Classic',
                'description' => "Narrated by the disillusioned Holden Caulfield, The Catcher in the Rye tells the story of a troubled teenager struggling with the death of his brother and his feelings of alienation in a world he perceives as phony. The novel explores themes of identity, innocence, and the complexity of adolescence.",
                'cover' => 'assets\\covers\\The Catcher in the Rye.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Pride and Prejudice',
                'author' => 'Jane Austen',
                'genre' => 'Fiction, Classic, Romance',
                'description' => "In this beloved classic, Elizabeth Bennet navigates societal pressures and family expectations as she develops a relationship with the proud but intriguing Mr. Darcy. With its witty dialogue and exploration of love, class, and societal norms, Pride and Prejudice remains one of the most celebrated works of English literature.",
                'cover' => 'assets\\covers\\Pride and Prejudice.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Shining',
                'author' => 'Stephen King',
                'genre' => 'Horror, Thriller, Psychological Fiction',
                'description' => "Jack Torrance, a struggling writer, accepts a job as the winter caretaker of the remote Overlook Hotel. When his family moves into the hotel for the season, strange and terrifying things begin to happen. As Jack becomes consumed by the hotel’s malevolent influence, his family’s safety is threatened.",
                'cover' => 'assets\\covers\\The Shining.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Dracula',
                'author' => 'Bram Stoker',
                'genre' => 'Horror, Gothic Fiction, Classic',
                'description' => "Count Dracula travels from Transylvania to England to spread the undead curse of vampirism. The novel follows several characters who fight to stop Dracula, including the determined Mina Harker, her fiancé Jonathan, and the renowned doctor Abraham Van Helsing.",
                'cover' => 'assets\\covers\\Dracula.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Frankenstein',
                'author' => 'Mary Shelley',
                'genre' => 'Horror, Gothic Fiction, Science Fiction',
                'description' => "A scientist named Victor Frankenstein creates a monstrous creature in an unorthodox scientific experiment. However, his creation is rejected by society, leading to a tragic and violent chain of events. The novel explores themes of creation, responsibility, and the consequences of unchecked ambition.",
                'cover' => 'assets\\covers\\Frankenstein.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Haunting of Hill House',
                'author' => 'Shirley Jackson',
                'genre' => 'Horror, Gothic Fiction, Psychological Horror',
                'description' => "Four people spend time in a supposedly haunted mansion called Hill House. The story explores their experiences in the house, particularly Eleanor Vance, who becomes increasingly obsessed with the house’s supernatural events. It’s a psychological horror story about isolation and fear.",
                'cover' => 'assets\\covers\\The Haunting of Hill House.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Bird Box',
                'author' => 'Josh Malerman',
                'genre' => 'Horror, Post-apocalyptic Fiction, Thriller',
                'description' => "In a world where a mysterious entity drives people to madness upon sight, Malorie must protect her two young children as they navigate a world where they must keep their eyes closed to survive. The tension of the unknown, combined with the terror of their dangerous surroundings, creates an intense atmosphere of horror.",
                'cover' => 'assets\\covers\\Bird Box.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'World War Z',
                'author' => 'Max Brooks',
                'genre' => 'Horror, Zombie Fiction, Apocalyptic Fiction',
                'description' => "This oral history of the global zombie war offers firsthand accounts from survivors as they recount the terrifying experiences of a world on the brink of collapse. Through a series of interviews, the novel reveals how society breaks down and the human cost of surviving the zombie apocalypse.",
                'cover' => 'assets\\covers\\World War Z.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Silence of the Lambs',
                'author' => 'Thomas Harris',
                'genre' => 'Horror, Psychological Thriller, Crime Fiction',
                'description' => "FBI trainee Clarice Starling seeks the help of imprisoned cannibalistic serial killer Dr. Hannibal Lecter to catch another serial killer, Buffalo Bill. As she delves into the mind of Lecter, she finds herself in a dangerous psychological battle.",
                'cover' => 'assets\\covers\\The Silence of the Lambs.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Exorcist',
                'author' => 'William Peter Blatty',
                'genre' => 'Horror, Supernatural Fiction, Thriller',
                'description' => "When a young girl named Regan begins exhibiting strange and violent behavior, her mother seeks the help of two priests to perform an exorcism. The story explores the terrifying battle between good and evil as the priests try to save Regan from the malevolent force possessing her.",
                'cover' => 'assets\\covers\\The Exorcist.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'It',
                'author' => 'Stephen King',
                'genre' => 'Horror, Thriller, Supernatural Fiction',
                'description' => "A group of children in the town of Derry, Maine, confronts an ancient evil that has taken the form of a monstrous clown named Pennywise. Years later, they return as adults to face the creature once again in this chilling story of friendship, fear, and the unknown.",
                'cover' => 'assets\\covers\\It.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'House of Leaves',
                'author' => 'Mark Z. Danielewski',
                'genre' => 'Horror, Psychological Horror, Experimental Fiction',
                'description' => "A young family moves into a house with strange, shifting dimensions. As they uncover the house’s dark secrets, a documentary filmmaker begins to unravel the mystery behind it. The novel combines horror, psychological tension, and experimental narrative techniques to create an unsettling and unique reading experience.",
                'cover' => 'assets\\covers\\House of Leaves.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Girl with the Dragon Tattoo',
                'author' => 'Stieg Larsson',
                'genre' => 'Thriller, Mystery, Crime Fiction',
                'description' => "Journalist Mikael Blomkvist and hacker Lisbeth Salander team up to investigate the disappearance of Harriet Vanger, a young woman who vanished over forty years ago. As they uncover dark family secrets and corporate corruption, they find themselves entangled in a dangerous conspiracy.",
                'cover' => 'assets\\covers\\The Girl with the Dragon Tattoo.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Gone Girl',
                'author' => 'Gillian Flynn',
                'genre' => 'Thriller, Mystery, Psychological Fiction',
                'description' => "When Amy Dunne goes missing on her fifth wedding anniversary, her husband Nick becomes the prime suspect in her disappearance. As the investigation unfolds, dark secrets about their marriage are revealed, and the truth becomes increasingly twisted and difficult to uncover.",
                'cover' => 'assets\\covers\\Gone Girl.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Silent Patient',
                'author' => 'Alex Michaelides',
                'genre' => 'Thriller, Mystery, Psychological Fiction',
                'description' => "A celebrated painter, Alicia Berenson, shoots her husband in the face five times and then never speaks again. Theo Faber, a psychotherapist, becomes obsessed with Alicia’s case and works to uncover the truth behind her silence. As he digs deeper, he uncovers shocking secrets.",
                'cover' => 'assets\\covers\\The Silent Patient.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Woman in the Window',
                'author' => 'A.J. Finn',
                'genre' => 'Thriller, Mystery, Psychological Fiction',
                'description' => "Anna Fox, an agoraphobic woman, spends her days watching her neighbors from her window. One day, she believes she witnesses a crime in the house across the street, but no one believes her. As she becomes increasingly unstable, she must unravel the truth about what really happened.",
                'cover' => 'assets\\covers\\The Woman in the Window.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Shutter Island',
                'author' => 'Dennis Lehane',
                'genre' => 'Thriller, Mystery, Psychological Fiction',
                'description' => "U.S. Marshal Teddy Daniels is sent to investigate the disappearance of a patient from a mental institution on Shutter Island. As he delves deeper into the mystery, he uncovers terrifying secrets about the island and begins questioning his own sanity.",
                'cover' => 'assets\\covers\\Shutter Island.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Dune',
                'author' => 'Frank Herbert',
                'genre' => 'Sci-Fi, Adventure, Epic',
                'description' => "Set in the distant future, 'Dune' follows Paul Atreides, a young nobleman whose family becomes embroiled in a battle for control of the desert planet Arrakis, the only source of the universe’s most valuable substance: the spice melange. As Paul learns of his destiny, he must navigate politics, religion, and ecological struggles.",
                'cover' => 'assets\\covers\\Dune.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Neuromancer',
                'author' => 'William Gibson',
                'genre' => 'Sci-Fi, Cyberpunk, Thriller',
                'description' => "Case, a washed-up computer hacker, is hired by a mysterious employer to carry out a dangerous mission in cyberspace. With his consciousness jacked into a virtual world, he must confront a powerful AI and the dark underworld of hackers, corporations, and artificial intelligence in a dystopian future.",
                'cover' => 'assets\\covers\\Neuromancer.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Left Hand of Darkness',
                'author' => 'Ursula K. Le Guin',
                'genre' => 'Sci-Fi, Adventure, Classic',
                'description' => "Genly Ai, a human envoy from the Ekumen, is sent to the planet Gethen to persuade its inhabitants to join an interplanetary alliance. But Gethen’s inhabitants are ambisexual, and Ai struggles to understand their culture. As tensions rise, Ai must navigate politics, survival, and an evolving friendship with Estravan, a local leader.",
                'cover' => 'assets\\covers\\The Left Hand of Darkness.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Martian',
                'author' => 'Andy Weir',
                'genre' => 'Sci-Fi, Adventure, Survival',
                'description' => "Astronaut Mark Watney is stranded alone on Mars after a space mission goes wrong. Presumed dead by his crew and Earth, Watney uses his engineering and botanical skills to survive, relying on wit, determination, and science to find a way to communicate with NASA and return home.",
                'cover' => 'assets\\covers\\The Martian.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => '',
                'author' => '',
                'genre' => '',
                'description' => "",
                'cover' => 'assets\\covers\\',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Hyperion',
                'author' => 'Dan Simmons',
                'genre' => 'Sci-Fi, Space Opera, Adventure',
                'description' => "In the distant future, seven pilgrims travel to the distant world of Hyperion, each with their own tale to tell. As they journey toward the distant planet, they share their stories of loss, love, and ambition, all connected by the mysterious Shrike, a creature said to be responsible for their fates.",
                'cover' => 'assets\\covers\\Hyperion.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Notebook',
                'author' => 'Nicholas Sparks',
                'genre' => 'Romance, Drama, Fiction',
                'description' => "Noah and Allie’s love story begins in the 1940s and continues through the years. Despite social differences and time apart, they find themselves drawn back to each other, facing the challenges of life, love, and memory loss in their later years.",
                'cover' => 'assets\\covers\\The Notebook.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Me Before You',
                'author' => 'Jojo Moyes',
                'genre' => 'Romance, Drama, Fiction',
                'description' => "Louisa Clark becomes a caregiver for Will Traynor, a wealthy man left paralyzed after an accident. Despite their differences, they develop a deep and transformative relationship, but Will’s desire to end his life leads to a heartbreaking conclusion.",
                'cover' => 'assets\\covers\\Me Before You.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Hating Game',
                'author' => 'Sally Thorne',
                'genre' => 'Romance, Comedy, Fiction',
                'description' => "Lucy Hutton and Joshua Templeman are coworkers who cannot stand each other. As they compete for a promotion at their publishing house, their animosity begins to shift into attraction, leading to a romantic tension that both of them struggle to understand.",
                'cover' => 'assets\\covers\\The Hating Game.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Kiss Quotient',
                'author' => 'Helen Hoang',
                'genre' => 'Romance, Contemporary, Fiction',
                'description' => "Stella Lane, a successful woman with Asperger’s, hires a male escort, Michael, to teach her about intimacy. As their professional relationship grows, so do their feelings for each other, leading them to navigate the complexities of love, vulnerability, and self-acceptance.",
                'cover' => 'assets\\covers\\The Kiss Quotient.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Kite Runner',
                'author' => 'Khaled Hosseini',
                'genre' => 'Fiction, Historical, Drama',
                'description' => "The Kite Runner tells the story of Amir, a boy from a wealthy family in Kabul, and his complex relationship with Hassan, the son of his father’s servant. As the story unfolds across Afghanistan and America, Amir must confront past betrayals, loss, and redemption in the wake of Afghanistan’s political upheaval.",
                'cover' => 'assets\\covers\\The Kite Runner.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Atonement',
                'author' => 'Ian McEwan',
                'genre' => 'Fiction, Historical, Romance',
                'description' => "Atonement follows the lives of three characters—Briony, Cecilia, and Robbie—as they are forever changed by a lie told in the heat of the moment. Set against the backdrop of World War II, the novel explores themes of guilt, atonement, and the consequences of one’s actions.",
                'cover' => 'assets\\covers\\Atonement.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Book Thief',
                'author' => 'Markus Zusak',
                'genre' => 'Fiction, Historical, Young Adult',
                'description' => "Narrated by Death, this novel tells the story of Liesel Meminger, a young girl growing up in Nazi Germany. As the war unfolds, Liesel steals books to share with others, all while confronting the harsh realities of the time and forming deep bonds with the people around her.",
                'cover' => 'assets\\covers\\The Book Thief.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Secret History',
                'author' => 'Donna Tartt',
                'genre' => 'Fiction, Thriller, Mystery',
                'description' => "The Secret History follows a group of college students who form an exclusive group under the guidance of a charismatic professor. As their obsession with an ancient Greek culture spirals out of control, they are drawn into a dark and dangerous world of murder and deception.",
                'cover' => 'assets\\covers\\The Secret History.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Life After Life',
                'author' => 'Kate Atkinson',
                'genre' => 'Fiction, Historical',
                'description' => "Life After Life explores the multiple lives of Ursula Todd, a woman who is repeatedly born and dies in different circumstances. The novel contemplates fate, choice, and the impact of small moments in shaping the course of history, as Ursula lives through the major events of the 20th century.",
                'cover' => 'assets\\covers\\Life After Life.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Thinking, Fast and Slow',
                'author' => 'Daniel Kahneman',
                'genre' => 'Psychology',
                'description' => "In this groundbreaking book, Nobel laureate Daniel Kahneman explores the two systems of thinking that drive our decisions: the fast, intuitive, and emotional system, and the slow, deliberate, and logical one. Kahneman discusses how both systems shape our judgments and decisions, and the biases that affect our thinking.",
                'cover' => 'assets\\covers\\Thinking Fast and Slow.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Power of Habit',
                'author' => 'Charles Duhigg',
                'genre' => 'Psychology, Self-Help, Behavioral Science',
                'description' => "The Power of Habit delves into the science behind habits and how they form, as well as the ways they can be changed. Duhigg explores how understanding the neurological loop of habit formation can help people break bad habits and create new ones to improve their personal and professional lives.",
                'cover' => 'assets\\covers\\The Power of Habit.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Quiet: The Power of Introverts in a World That Can’t Stop Talking',
                'author' => 'Susan Cain',
                'genre' => 'Psychology, Personal Development',
                'description' => "In Quiet, Susan Cain makes the case for the power of introverts in a world that seems to value extroversion. She explores the psychology of introversion, its impact on leadership, creativity, and relationships, and how introverts can thrive in a world that tends to favor the outgoing.",
                'cover' => 'assets\\covers\\Quiet The Power of Introverts in a World That Can’t Stop Talking.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Outliers: The Story of Success',
                'author' => 'Malcolm Gladwell',
                'genre' => 'Psychology, Sociology, Self-Help',
                'description' => "Outliers challenges the traditional notion of the self-made success and explores the factors that contribute to extraordinary achievement. Gladwell discusses how opportunity, culture, timing, and hard work play a greater role in success than individual talent alone.",
                'cover' => 'assets\\covers\\Outliers The Story of Success.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Influence: The Psychology of Persuasion',
                'author' => 'Robert B. Cialdini',
                'genre' => 'Psychology, Marketing, Self-Help',
                'description' => "In Influence, Dr. Robert Cialdini explores the psychology behind why people say 'yes' and how to apply these understandings in various aspects of life. Cialdini identifies six principles of persuasion—reciprocity, commitment, social proof, authority, liking, and scarcity—and how they shape our behaviors.",
                'cover' => 'assets\\covers\\Influence The Psychology of Persuasion.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Man’s Search for Meaning',
                'author' => 'Viktor E. Frankl',
                'genre' => 'Psychology, Philosophy, Self-Help',
                'description' => "In Man’s Search for Meaning, psychiatrist Viktor Frankl reflects on his experiences as a Holocaust survivor and the role that finding meaning in life played in his survival. Frankl introduces his philosophy of logotherapy, which emphasizes the importance of meaning in overcoming suffering and achieving a fulfilled life.",
                'cover' => 'assets\\covers\\Mans Search for Meaning.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Social Animal',
                'author' => 'Elliot Aronson',
                'genre' => 'Psychology',
                'description' => "The Social Animal is a comprehensive exploration of human behavior, delving into the forces that shape our attitudes, beliefs, and actions. Aronson uses real-world examples and research to highlight the key concepts of social psychology, such as conformity, persuasion, and the influence of others.",
                'cover' => 'assets\\covers\\The Social Animal.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Grit: The Power of Passion and Perseverance',
                'author' => 'Angela Duckworth',
                'genre' => 'Psychology, Personal Development',
                'description' => "In Grit, Angela Duckworth argues that passion and perseverance—what she calls 'grit'—are the most important predictors of success. Drawing on research in psychology and real-life examples, Duckworth shows how cultivating grit can help individuals achieve long-term goals and overcome obstacles.",
                'cover' => 'assets\\covers\\Grit The Power of Passion and Perseverance.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Psychopath Test',
                'author' => 'Jon Ronson',
                'genre' => 'Psychology, Non-fiction, Humor',
                'description' => "The Psychopath Test is an exploration of the science and psychology behind psychopathy, taking readers through the diagnostic process and examining the cultural implications of psychopathy in both individuals and society. Ronson combines personal narrative, investigative journalism, and humor to explore this complex topic.",
                'cover' => 'assets\\covers\\The Psychopath Test.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Seven Principles for Making Marriage Work',
                'author' => 'John Gottman',
                'genre' => 'Psychology, Relationships, Self-Help',
                'description' => "In this book, Dr. John Gottman offers research-based strategies for building strong, lasting relationships. Focusing on the key aspects of communication, conflict resolution, and emotional connection, the book provides practical advice for couples looking to improve their marriage or long-term relationship.",
                'cover' => 'assets\\covers\\The Seven Principles for Making Marriage Work.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Reversal',
                'author' => 'Michael Connelly',
                'genre' => 'Mystery, Thriller, Crime Fiction',
                'description' => "Mickey Haller, a defense attorney, is brought back into the legal world to work as a prosecutor in a case involving a man convicted of murder who wants to overturn his conviction. As Haller digs deeper, he uncovers a web of deceit, corruption, and new revelations that threaten to destroy everything.",
                'cover' => 'assets\\covers\\The Reversal.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'In the Woods',
                'author' => 'Tana French',
                'genre' => 'Mystery, Psychological Fiction, Thriller',
                'description' => "A detective, Rob Ryan, is sent to investigate the murder of a young girl in a small Irish town that holds a personal connection to his past. As he delves into the case, his buried memories resurface, making him question his own involvement and uncovering more than he expected.",
                'cover' => 'assets\\covers\\In the Woods.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Sharp Objects',
                'author' => 'Gillian Flynn',
                'genre' => 'Mystery, Psychological Fiction, Thriller',
                'description' => "Camille Preaker, a journalist, returns to her hometown to investigate the brutal murders of two pre-teen girls. As she delves into the case, she is forced to confront her own traumatic past, leading to a shocking and twisted revelation about the town and her family.",
                'cover' => 'assets\\covers\\Sharp Objects.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Before I Go to Sleep',
                'author' => '',
                'genre' => 'Mystery, Psychological Fiction, Thriller',
                'description' => "Christine Lucas wakes up every day with no memory of who she is due to amnesia caused by a traumatic incident. Each day, her therapist helps her piece together her life, but as she uncovers more about her past, she begins to question everyone around her and the truth about her condition.",
                'cover' => 'assets\\covers\\Before I Go to Sleep.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Very Hungry Caterpillar',
                'author' => 'Eric Carle',
                'genre' => 'Children’s, Picture Book, Classic',
                'description' => "A caterpillar eats through a variety of foods before transforming into a beautiful butterfly. This classic story teaches children about counting, the days of the week, and the process of metamorphosis.",
                'cover' => 'assets\\covers\\The Very Hungry Caterpillar.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Where the Wild Things Are',
                'author' => 'Maurice Sendak',
                'genre' => 'Children’s, Picture Book, Fantasy',
                'description' => "Max, a young boy, sails to an island where he meets wild creatures that crown him as their king. This timeless story is about imagination, adventure, and the power of love and home.",
                'cover' => 'assets\\covers\\Where the Wild Things Are.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Goodnight Moon',
                'author' => 'Margaret Wise Brown',
                'genre' => 'Children’s, Bedtime, Picture Book',
                'description' => "A beloved bedtime story that features a little bunny saying goodnight to everything in his room, from the moon to the red balloon. It’s a comforting and rhythmic story perfect for young children.",
                'cover' => 'assets\\covers\\Goodnight Moon.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Gruffalo',
                'author' => 'Julia Donaldson',
                'genre' => 'Children’s, Picture Book, Fantasy',
                'description' => "A little mouse goes on a journey through the forest and uses her wits to escape from predators by inventing a mythical creature called the Gruffalo. This delightful story is full of rhymes and cleverness.",
                'cover' => 'assets\\covers\\The Gruffalo.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Matilda',
                'author' => 'Roald Dahl',
                'genre' => 'Children’s, Fiction, Fantasy',
                'description' => "Matilda is a young girl with extraordinary intelligence and telekinetic powers. She uses her gifts to stand up against her cruel parents and the tyrannical school headmistress, Miss Trunchbull, in this charming and empowering tale.",
                'cover' => 'assets\\covers\\Matilda.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Charlotte’s Web',
                'author' => 'E.B. White',
                'genre' => 'Children’s, Fiction, Classic',
                'description' => "The story of a pig named Wilbur and his friendship with Charlotte, a clever spider who uses her web to save Wilbur’s life. This classic story is about friendship, loyalty, and the cycle of life.",
                'cover' => 'assets\\covers\\Charlottes Web.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Cat in the Hat',
                'author' => 'Dr. Seuss',
                'genre' => 'Children’s, Picture Book, Classic',
                'description' => "Two children are stuck inside on a rainy day when a mischievous cat in a tall striped hat shows up and creates chaos with his antics. This classic tale teaches children about imagination and the fun of mischief.",
                'cover' => 'assets\\covers\\The Cat in the Hat.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'The Little Engine That Could',
                'author' => 'Watty Piper',
                'genre' => 'Children’s, Picture Book, Motivational',
                'description' => "A little blue engine faces a difficult challenge when it is asked to pull a train full of toys over a mountain. With determination and the belief that it can, the little engine succeeds in delivering the toys to children on the other side.",
                'cover' => 'assets\\covers\\The Little Engine That Could.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Alice’s Adventures in Wonderland',
                'author' => 'Lewis Carroll',
                'genre' => 'Children’s, Fantasy, Adventure',
                'description' => "Alice follows a white rabbit down a hole and enters a fantastical world full of strange characters, puzzles, and absurdities. This imaginative adventure encourages curiosity and self-discovery.",
                'cover' => 'assets\\covers\\Alices Adventures in Wonderland.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ],
            [
                'title' => 'Winnie The Pooh',
                'author' => 'A.A. Milne',
                'genre' => 'Children’s, Classic, Fiction',
                'description' => "The adventures of Winnie-the-Pooh and his friends in the Hundred Acre Wood, as they go on playful quests and explore themes of friendship, loyalty, and simplicity.",
                'cover' => 'assets\\covers\\Winnie The Pooh.jpg',
                'created_at' => now(),
                'updated_at' => now(),
                'release_date' => NULL,
            ]
        ]);
    }
}