<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RepliesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('replies')->insert([
            [
                'review_id' => 1,
                'user_id' => 3,
                'comment' => 'Absolutely! Suzanne Collins masterfully weaves a story that\'s as emotional as it is thrilling. Katniss\'s strength and resilience make her such a compelling protagonist, and the tension in the Games is unmatched.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 1,
                'user_id' => 15,
                'comment' => 'It’s such a page-turner!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 16,
                'user_id' => 22,
                'comment' => 'The humor truly shines amidst the chaos, making every moment unforgettable and surprisingly uplifting.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 20,
                'user_id' => 10,
                'comment' => 'Its magical charm and emotional depth set the perfect tone for a story that resonates with readers of all ages.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 24,
                'user_id' => 27,
                'comment' => 'The seamless blend of wit and depth makes this an extraordinary tale that’s both entertaining and thought-provoking.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 52,
                'user_id' => 48,
                'comment' => 'The emotional intensity of this sequel hits hard, weaving love and resilience into an unforgettable narrative.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 3,
                'user_id' => 37,
                'comment' => 'The raw portrayal of war’s toll gives the finale an emotional weight that lingers long after the last page.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 90,
                'user_id' => 16,
                'comment' => 'With its gripping pace and dynamic characters, it keeps you hooked from start to finish.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 5,
                'user_id' => 32,
                'comment' => 'Its psychological depth and relentless twists keep you captivated as it delves into human struggles and survival.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 6,
                'user_id' => 46,
                'comment' => 'A bittersweet finale that challenges expectations, leaving a lasting impression despite its divisive ending.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 7,
                'user_id' => 39,
                'comment' => 'The perfect mix of action and intrigue makes it impossible to put down until the very end.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 8,
                'user_id' => 33,
                'comment' => 'The added intensity and danger elevate the series to thrilling new heights.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 9,
                'user_id' => 47,
                'comment' => 'A solid conclusion that wraps up the journey, even if some moments feel a bit predictable.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 10,
                'user_id' => 24,
                'comment' => 'Packed with humor and heart, this adventure is a delightful ride from start to finish.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 11,
                'user_id' => 35,
                'comment' => 'The twists and fast-paced action make it a must-read for fans of clever, high-stakes thrillers.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 12,
                'user_id' => 49,
                'comment' => 'The mix of dark humor and unpredictable turns makes this apocalyptic tale unforgettable.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 71,
                'user_id' => 1,
                'comment' => 'Its heartfelt exploration of love and loss lingers with you long after the final page.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 14,
                'user_id' => 16,
                'comment' => 'A darkly humorous and charming story that celebrates life\'s quirks and imperfections.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 15,
                'user_id' => 41,
                'comment' => 'A wonderfully entertaining blend of sci-fi and heartfelt moments, with characters that truly shine.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 17,
                'user_id' => 2,
                'comment' => 'Its mix of humor and insight into life’s absurdities makes it a truly engaging and reflective read.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 18,
                'user_id' => 25,
                'comment' => 'The heartfelt honesty and humor create a memoir that’s both entertaining and uplifting.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 19,
                'user_id' => 11,
                'comment' => 'A profound and relatable tale that captures the resilience of the human spirit beautifully.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 21,
                'user_id' => 5,
                'comment' => 'The seamless blend of humor and depth makes this an unforgettable and emotional journey.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 22,
                'user_id' => 28,
                'comment' => 'Its fast-paced adventure and richly developed characters make every page a thrill.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 23,
                'user_id' => 1,
                'comment' => 'A delightfully absurd and clever story filled with wit and charm.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 25,
                'user_id' => 23,
                'comment' => 'The blend of wit and reflection makes it a poignant and memorable read.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 92,
                'user_id' => 13,
                'comment' => 'Full of wit and wisdom, this follow-up adds even more depth and hilarity to the story.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 56,
                'user_id' => 17,
                'comment' => 'Both hilarious and heartfelt, its emotional highs and lows resonate deeply.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 28,
                'user_id' => 7,
                'comment' => 'A uniquely honest take on resilience, blending humor with touching personal insights.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 29,
                'user_id' => 33,
                'comment' => 'A darkly comedic masterpiece with unforgettable characters and sharp societal critiques.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 30,
                'user_id' => 47,
                'comment' => 'Its satirical brilliance captures the absurdity of life and leaves a lasting impact.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 32,
                'user_id' => 21,
                'comment' => ' A beautifully woven tale that’s as thought-provoking as it is captivating.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 33,
                'user_id' => 41,
                'comment' => 'The perfect mix of humor, action, and heartfelt moments keeps readers enthralled.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 34,
                'user_id' => 8,
                'comment' => 'Insightful and uplifting, its humor and honesty make the journey relatable and inspiring.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 36,
                'user_id' => 2,
                'comment' => 'Its rich narrative balances complex relationships with gripping world-building.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 37,
                'user_id' => 43,
                'comment' => 'A timeless tale filled with warmth, adventure, and the search for belonging.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 38,
                'user_id' => 30,
                'comment' => 'A timeless tale filled with warmth, adventure, and the search for belonging.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 39,
                'user_id' => 44,
                'comment' => 'A masterful blend of cleverness, adventure, and philosophical depth.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 40,
                'user_id' => 18,
                'comment' => 'A stunning exploration of morality and survival wrapped in a compelling narrative.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 41,
                'user_id' => 14,
                'comment' => 'Its deep emotional themes and vivid storytelling make it unforgettable.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 42,
                'user_id' => 26,
                'comment' => 'A captivating tale with exceptional world-building and powerful character arcs.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 43,
                'user_id' => 38,
                'comment' => 'A poignant exploration of ambition and love set in a beautifully rendered era.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 44,
                'user_id' => 39,
                'comment' => 'A timeless story that delves deeply into empathy and justice, leaving a lasting impression.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 45,
                'user_id' => 9,
                'comment' => 'A gripping and chilling exploration of control and the resilience of the human spirit.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 46,
                'user_id' => 35,
                'comment' => 'Its raw and relatable narrative captures the struggles of growing up beautifully.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 47,
                'user_id' => 41,
                'comment' => 'A delightful look at human nature, with characters and wit that endure through time.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 48,
                'user_id' => 12,
                'comment' => 'Its eerie atmosphere and intense twists keep you riveted until the very end.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 49,
                'user_id' => 21,
                'comment' => 'A hauntingly immersive classic filled with intrigue and timeless suspense.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 54,
                'user_id' => 40,
                'comment' => 'A deeply human story of tragedy and redemption that resonates across generations.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 50,
                'user_id' => 30,
                'comment' => 'Its chilling exploration of fear and the human psyche is perfectly paced and utterly compelling.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 108,
                'user_id' => 6,
                'comment' => 'The constant tension and fear of the unknown make this a truly unforgettable thriller. A terrifying reminder of the dangers we can\'t see.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 109,
                'user_id' => 43,
                'comment' => 'A gripping look at humanity\'s survival instinct during a global crisis. The global scope makes it feel both real and terrifying.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 110,
                'user_id' => 18,
                'comment' => 'The deep dive into the psyche of both predator and prey creates an unforgettable tension. A chilling read from start to finish.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 111,
                'user_id' => 39,
                'comment' => 'The battle between good and evil is terrifyingly real in this iconic horror. It will haunt you long after you finish.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 112,
                'user_id' => 31,
                'comment' => 'A story that mixes nostalgia with horror, where childhood fears come to life. The bond of friendship truly adds depth to the terror.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 113,
                'user_id' => 9,
                'comment' => 'A disorienting and immersive narrative that keeps you questioning reality. It\'s a truly unique reading experience.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 114,
                'user_id' => 23,
                'comment' => 'A riveting mystery that pulls you deep into its web of secrets. The tension never lets up.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 115,
                'user_id' => 40,
                'comment' => 'A psychological rollercoaster where nothing is what it seems. The twists will keep you second-guessing everything.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 116,
                'user_id' => 45,
                'comment' => 'The mystery behind Alicia’s silence keeps you hooked until the very end. A masterclass in suspense and psychology.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 117,
                'user_id' => 29,
                'comment' => 'A gripping, unreliable narrative that keeps you guessing until the very last page. The suspense is palpable.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 118,
                'user_id' => 37,
                'comment' => 'A dark, atmospheric thriller that messes with your perception of reality. The ending will blow your mind.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 119,
                'user_id' => 22,
                'comment' => 'A captivating blend of politics and survival set in a fascinating, vast desert world that’s a must for any sci-fi fan.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 120,
                'user_id' => 44,
                'comment' => 'A bold vision of the future that challenges the boundaries of technology and human experience.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 121,
                'user_id' => 19,
                'comment' => 'A beautifully crafted exploration of identity and connection, with a world like no other.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 122,
                'user_id' => 45,
                'comment' => 'An inspiring story of survival with humor and science, showcasing resilience in the most extreme conditions.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 123,
                'user_id' => 31,
                'comment' => 'A beautifully complex narrative that intertwines seven stories with an eerie, unforgettable presence.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 124,
                'user_id' => 4,
                'comment' => 'A tender and emotional love story that resonates deeply and stands the test of time.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 125,
                'user_id' => 14,
                'comment' => 'A deeply moving tale that explores love, loss, and what it means to live fully.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 126,
                'user_id' => 24,
                'comment' => 'A delightful and humorous romance, full of tension and witty exchanges.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 127,
                'user_id' => 50,
                'comment' => 'A heartwarming and steamy romance that explores vulnerability, love, and self-discovery.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 128,
                'user_id' => 34,
                'comment' => 'A moving and emotional story of friendship and forgiveness, with a depth that lingers.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 129,
                'user_id' => 41,
                'comment' => 'A tragic yet beautifully written tale of guilt, loss, and the consequences of one lie.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 130,
                'user_id' => 35,
                'comment' => 'A powerful story of love, loss, and resilience, with Death\'s unique voice bringing a new perspective.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 131,
                'user_id' => 44,
                'comment' => 'A haunting tale of obsession, moral decay, and the darkness within the human soul.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 132,
                'user_id' => 13,
                'comment' => 'A thought-provoking exploration of fate and the many possible paths life can take.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 133,
                'user_id' => 29,
                'comment' => 'A captivating insight into the mind’s workings, altering how we view decision-making.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 134,
                'user_id' => 10,
                'comment' => 'An empowering exploration of how habits shape lives, offering practical insights for change.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 135,
                'user_id' => 19,
                'comment' => 'A vital read that highlights the strength and power of introverts in a noisy world.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 136,
                'user_id' => 3,
                'comment' => 'Gladwell’s entertaining and insightful stories challenge our perceptions of success.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 137,
                'user_id' => 11,
                'comment' => 'A must-read for anyone looking to understand the subtle forces that shape decisions.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 138,
                'user_id' => 25,
                'comment' => 'A profound journey into human resilience and the search for purpose, making it a life-changing read.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 139,
                'user_id' => 7,
                'comment' => 'A deep dive into social psychology, filled with fascinating research that’s both engaging and educational.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 140,
                'user_id' => 26,
                'comment' => 'A motivating call to embrace challenges and the power of persistence in achieving success.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 141,
                'user_id' => 20,
                'comment' => 'A quirky yet eye-opening journey into the world of psychopathy, with humor that makes the subject accessible.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 142,
                'user_id' => 5,
                'comment' => 'Gottman’s research-backed guide offers practical and insightful advice for building strong relationships.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 143,
                'user_id' => 28,
                'comment' => 'A legal thriller that’s full of twists, with Mickey Haller’s perspective adding depth and complexity.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 144,
                'user_id' => 12,
                'comment' => 'A gripping mystery that’s just as much about the characters\' emotional journeys as the crime itself.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 145,
                'user_id' => 47,
                'comment' => 'I think so too!',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 146,
                'user_id' => 20,
                'comment' => 'The constant suspense and the unraveling of Christine’s memory make every page turn more intense. It\'s a truly unforgettable psychological journey.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 147,
                'user_id' => 6,
                'comment' => 'The simple yet captivating narrative is perfect for sparking curiosity about nature and transformation.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 148,
                'user_id' => 15,
                'comment' => 'The emotional depth of Max’s journey makes it a beautiful and relatable story for all ages.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 149,
                'user_id' => 4,
                'comment' => 'Its peaceful rhythm and gentle tone make it the perfect bedtime story, lulling children to sleep with ease.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 150,
                'user_id' => 36,
                'comment' => 'A fun and engaging read, the Gruffalo’s cleverness and humor make it a joy for both children and adults.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 151,
                'user_id' => 17,
                'comment' => 'A wonderful tale of a girl’s strength and intelligence, showing that standing up for yourself is a powerful thing.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 152,
                'user_id' => 34,
                'comment' => 'The bond between Charlotte and Wilbur is a beautiful reminder of selfless friendship and loyalty.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 153,
                'user_id' => 42,
                'comment' => 'Dr. Seuss’s playful language and vivid illustrations create a world of wonder and fun.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 154,
                'user_id' => 27,
                'comment' => 'The little engine’s mantra is a lesson in determination and optimism, inspiring readers to keep going.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 155,
                'user_id' => 8,
                'comment' => 'Alice’s curiosity and the bizarre world she explores remind us of the endless possibilities of imagination.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'review_id' => 156,
                'user_id' => 50,
                'comment' => 'A heartwarming collection of tales filled with wisdom and gentle humor. Pooh’s adventures are a joy to read. Its themes of friendship and kindness make it an evergreen favorite for all readers.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
