<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ReviewsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
{
    DB::table('reviews')->insert([
        [
            'userID' => 2,
            'bookID' => 1,
            'rating' => 5,
            'comment' => "A gripping dystopian novel that keeps you on the edge of your seat. Katniss's journey is both heart-wrenching and inspiring.",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 3,
            'bookID' => 2,
            'rating' => 4,
            'comment' => "The sequel to The Hunger Games surpasses the first book with more intense action and deeper character development.",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 4,
            'bookID' => 3,
            'rating' => 4,
            'comment' => "A powerful conclusion to the trilogy that explores the complexities of war and sacrifice, though it leaves you with mixed emotions.",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 5,
            'bookID' => 4,
            'rating' => 4,
            'comment' => "An intriguing world with a strong, independent heroine, though the pacing slows down at times.",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 6,
            'bookID' => 5,
            'rating' => 4,
            'comment' => "A thrilling continuation with unexpected twists and deeper world-building. The stakes are raised higher.",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 7,
            'bookID' => 6,
            'rating' => 3,
            'comment' => "An emotional rollercoaster that ties up the series, though the ending is polarizing for many readers.",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 8,
            'bookID' => 7,
            'rating' => 4,
            'comment' => "A fast-paced thriller with mystery and action that keeps you guessing until the very end.",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 9,
            'bookID' => 8,
            'rating' => 4,
            'comment' => "A worthy follow-up to The Maze Runner. The Scorch Trials add even more danger and excitement to the series.",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 10,
            'bookID' => 9,
            'rating' => 4,
            'comment' => "A satisfying conclusion to the Maze Runner series that ties up all loose ends, though it can be a bit predictable at times.",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 11,
            'bookID' => 10,
            'rating' => 4,
            'comment' => "A fun, adventurous read with likable characters. The plot keeps moving at a fast pace, and there's plenty of humor along the way.",
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 12,
            'bookID' => 11,
            'rating' => 4,
            'comment' => 'A thrilling heist novel with unexpected twists. The characters are well-developed and the plot is full of action.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 13,
            'bookID' => 12,
            'rating' => 4,
            'comment' => 'An incredibly unique and funny take on the apocalypse. The characters are hilarious, and the plot has plenty of twists and turns.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 14,
            'bookID' => 13,
            'rating' => 4,
            'comment' => 'A thrilling ride from start to finish, with plenty of action and high stakes. It keeps you on the edge of your seat the whole time.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 15,
            'bookID' => 14,
            'rating' => 4,
            'comment' => 'A quirky and fun look at the absurdities of life. The characters are eccentric, and the humor is dark but endearing.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 16,
            'bookID' => 15,
            'rating' => 4,
            'comment' => 'A unique blend of sci-fi and humor. The characters are relatable, and the storyline is surprisingly heartwarming.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 17,
            'bookID' => 16,
            'rating' => 5,
            'comment' => 'A heartbreaking and hilarious memoir. The author\'s wit and humor make light of difficult experiences in a way that is relatable and refreshing.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 18,
            'bookID' => 17,
            'rating' => 4,
            'comment' => 'A deeply reflective and thought-provoking book about the quirks of life. It captures the absurdity of growing up in a funny and accessible way.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 19,
            'bookID' => 18,
            'rating' => 4,
            'comment' => 'A heartwarming memoir full of humor and honesty. The author’s ability to find joy in the most awkward moments is refreshing and entertaining.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 20,
            'bookID' => 19,
            'rating' => 4,
            'comment' => 'A hilarious, yet insightful, look at life through a very unique lens. It provides both humor and heartfelt moments.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 21,
            'bookID' => 20,
            'rating' => 5,
            'comment' => 'A brilliant and emotional memoir. The humor in this book will make you laugh out loud, but the poignant moments will leave you thinking long after.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 22,
            'bookID' => 21,
            'rating' => 5,
            'comment' => 'An absolutely fantastic and emotional novel. The way the author mixes humor with deep themes is impressive and touching.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 23,
            'bookID' => 22,
            'rating' => 4,
            'comment' => 'A thrilling and fast-paced adventure with a fun twist. The characters are full of depth and bring the story to life.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 24,
            'bookID' => 23,
            'rating' => 4,
            'comment' => 'A gripping story that you won\'t be able to put down. The suspense and character development are top-notch.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 25,
            'bookID' => 24,
            'rating' => 5,
            'comment' => 'A captivating start to an unforgettable journey. The characters are deeply compelling, and the world-building is exceptional.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 26,
            'bookID' => 25,
            'rating' => 4,
            'comment' => 'A beautifully written and heart-wrenching novel about love, loss, and survival. It’s hard to put down once you start.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 27,
            'bookID' => 26,
            'rating' => 4,
            'comment' => 'A strong follow-up to the first book in the series, with more action and even higher stakes. Truly a must-read for fans of the genre.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 28,
            'bookID' => 27,
            'rating' => 4,
            'comment' => 'An emotional rollercoaster with characters that feel real and grounded. The ending will leave you breathless.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 29,
            'bookID' => 28,
            'rating' => 4,
            'comment' => 'A compelling narrative with a strong message about personal growth and resilience. The plot is full of twists that keep you engaged.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 30,
            'bookID' => 29,
            'rating' => 4,
            'comment' => 'A fun, fast-paced adventure with well-crafted characters. The stakes are high, and the action never lets up.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 31,
            'bookID' => 30,
            'rating' => 5,
            'comment' => 'An inspiring and uplifting story about finding your path in the world. The author’s voice is full of warmth and wisdom.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 31,
            'bookID' => 32,
            'rating' => 4,
            'comment' => 'A funny and thought-provoking exploration of life’s complexities. The humor is sharp, and the insights are valuable.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 32,
            'bookID' => 33,
            'rating' => 4,
            'comment' => 'An intellectual and philosophical journey that challenges your assumptions. It’s not an easy read, but it’s worth every moment.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 33,
            'bookID' => 34,
            'rating' => 5,
            'comment' => 'A hilarious and heartwarming story about finding meaning in the absurd. The author’s wit shines through every page.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 34,
            'bookID' => 35,
            'rating' => 4,
            'comment' => 'An insightful and relatable memoir about navigating the awkwardness of growing up. The humor makes the hard moments bearable.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 35,
            'bookID' => 36,
            'rating' => 4,
            'comment' => 'A fascinating, deeply personal exploration of modern life. It blends humor with sharp observations about culture and technology.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 36,
            'bookID' => 37,
            'rating' => 4,
            'comment' => 'An incredibly engaging and thought-provoking narrative. The story delves into the complexities of human relationships with humor and depth.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 37,
            'bookID' => 38,
            'rating' => 5,
            'comment' => 'A beautifully written and emotionally powerful book. It deals with complex themes of identity and belonging in a compelling way.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 38,
            'bookID' => 39,
            'rating' => 5,
            'comment' => 'A rich and immersive novel with stunning world-building. The characters’ emotional journeys are what make this book stand out.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 39,
            'bookID' => 40,
            'rating' => 4,
            'comment' => 'A gripping and thought-provoking science fiction story. The author masterfully combines adventure with deep philosophical questions about humanity.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 40,
            'bookID' => 41,
            'rating' => 5,
            'comment' => 'A true classic that stands the test of time. The themes of war, survival, and morality are timeless and thought-provoking.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 41,
            'bookID' => 42,
            'rating' => 4,
            'comment' => 'An unforgettable story that delves into deep themes of humanity and love. It’s a hard-hitting and emotionally charged read.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 42,
            'bookID' => 43,
            'rating' => 4,
            'comment' => 'A compelling narrative that tackles issues of isolation and identity. The plot twists and character development are excellent.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 43,
            'bookID' => 44,
            'rating' => 4,
            'comment' => 'A gripping and intense horror novel that explores the darker sides of the human mind. Definitely not for the faint of heart.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 44,
            'bookID' => 45,
            'rating' => 5,
            'comment' => 'A chilling and unsettling story that keeps you on the edge of your seat. It’s a must-read for fans of psychological horror.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 45,
            'bookID' => 46,
            'rating' => 4,
            'comment' => 'A gripping novel that tackles themes of control, fear, and survival. The tension builds up and never lets go.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 46,
            'bookID' => 47,
            'rating' => 4,
            'comment' => 'A thrilling and suspenseful story about survival in the face of overwhelming odds. The writing keeps you hooked from start to finish.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 47,
            'bookID' => 48,
            'rating' => 4,
            'comment' => 'A dark and thought-provoking tale about the complexities of human nature. The characters are flawed but captivating.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 48,
            'bookID' => 49,
            'rating' => 4,
            'comment' => 'A fast-paced and thrilling mystery that keeps you guessing until the very end. The plot twists are absolutely shocking.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 49,
            'bookID' => 50,
            'rating' => 5,
            'comment' => 'A masterfully written psychological thriller. The characters and the plot are deep and engaging. A page-turner from start to finish.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 50,
            'bookID' => 52,
            'rating' => 4,
            'comment' => 'A gripping and thought-provoking novel that explores the consequences of greed and betrayal. The pacing is perfect.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 51,
            'bookID' => 7,
            'rating' => 5,
            'comment' => 'An outstanding work of literary fiction that explores the complexities of love, loss, and redemption. A must-read for fans of contemporary fiction.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 52,
            'bookID' => 2,
            'rating' => 4,
            'comment' => 'A heartbreaking and beautiful story that examines the fragility of life and the power of love. It’s a deeply emotional read.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 53,
            'bookID' => 50,
            'rating' => 4,
            'comment' => 'An insightful and moving memoir that sheds light on the human experience in a way that feels both personal and universal.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 54,
            'bookID' => 51,
            'rating' => 5,
            'comment' => 'A powerful and moving story that blends tragedy and triumph. The characters are relatable and deeply human.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 55,
            'bookID' => 17,
            'rating' => 4,
            'comment' => 'A humorous and poignant novel about navigating the ups and downs of life. The author’s wit and insight are spot-on.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 56,
            'bookID' => 27,
            'rating' => 4,
            'comment' => 'A cleverly written and laugh-out-loud funny memoir. The author’s humor shines through, making for an entertaining read.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 7,
            'bookID' => 8,
            'rating' => 4,
            'comment' => 'An insightful exploration of life’s complexities, with humor and depth. The memoir captures both the absurd and the beautiful aspects of existence.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 5,
            'bookID' => 19,
            'rating' => 5,
            'comment' => 'A deeply emotional and honest portrayal of the human experience. It’s a story about finding meaning in a world full of challenges.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 9,
            'bookID' => 40,
            'rating' => 5,
            'comment' => 'A fascinating and richly detailed fantasy novel with a strong, unique world-building element. The plot and characters are engrossing.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 30,
            'bookID' => 12,
            'rating' => 5,
            'comment' => 'A truly epic and immersive fantasy novel. The world-building is top-notch, and the story keeps you captivated from beginning to end.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 21,
            'bookID' => 28,
            'rating' => 4,
            'comment' => 'A fantastic and fast-paced story with rich characters. The mystery and adventure elements keep you hooked all the way through.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 12,
            'bookID' => 36,
            'rating' => 4,
            'comment' => 'An emotional and beautifully written novel about love, loss, and second chances. A truly heartwarming and moving experience.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 11,
            'bookID' => 42,
            'rating' => 4,
            'comment' => 'An exciting adventure filled with twists and turns. The writing is brilliant, and the plot keeps you on the edge of your seat.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 4,
            'bookID' => 25,
            'rating' => 4,
            'comment' => 'A thought-provoking and poignant story about human connection and the impact of our choices. A great read for those who enjoy deep themes.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 6,
            'bookID' => 9,
            'rating' => 5,
            'comment' => 'A beautiful and emotional coming-of-age story that captures the essence of growing up and the relationships that shape us.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 50,
            'bookID' => 44,
            'rating' => 4,
            'comment' => 'A gripping and intense tale of survival. The action is nonstop, and the stakes are high from start to finish.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 16,
            'bookID' => 51,
            'rating' => 4,
            'comment' => 'An insightful and well-crafted novel that tackles difficult subjects with care and sensitivity. A must-read for fans of contemporary fiction.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 28,
            'bookID' => 3,
            'rating' => 4,
            'comment' => 'A charming and lighthearted novel about love and relationships. It’s a fun and quick read, but with a surprising amount of depth.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 39,
            'bookID' => 17,
            'rating' => 5,
            'comment' => 'An inspiring story about resilience and the power of the human spirit. It’s both heart-wrenching and uplifting.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 40,
            'bookID' => 48,
            'rating' => 4,
            'comment' => 'A suspenseful and thrilling mystery that keeps you guessing until the end. The plot twists are expertly executed.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 31,
            'bookID' => 13,
            'rating' => 5,
            'comment' => 'A beautifully written and deeply moving story about love, loss, and redemption. The characters feel so real, and the story stays with you long after you finish.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 42,
            'bookID' => 11,
            'rating' => 4,
            'comment' => 'A fun and quirky tale that blends humor and heart. It’s an enjoyable read with lovable characters and plenty of charm.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 53,
            'bookID' => 33,
            'rating' => 4,
            'comment' => 'A thrilling and thought-provoking novel about the consequences of technological advancements. A fascinating read for fans of dystopian fiction.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 54,
            'bookID' => 5,
            'rating' => 4,
            'comment' => 'A gripping and intense psychological thriller that explores the darker side of human nature. The suspense is palpable, and the twists are unexpected.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 35,
            'bookID' => 20,
            'rating' => 5,
            'comment' => 'A dark and powerful novel about survival in a broken world. The characters are complex, and the story explores deep themes about humanity.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 26,
            'bookID' => 32,
            'rating' => 4,
            'comment' => 'An exciting and well-paced adventure that mixes fantasy and mystery. The plot is full of intrigue and keeps you engaged throughout.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 27,
            'bookID' => 50,
            'rating' => 5,
            'comment' => 'A beautifully written story about love and personal growth. The characters are rich and relatable, and the narrative is heartfelt and authentic.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 18,
            'bookID' => 7,
            'rating' => 4,
            'comment' => 'A lighthearted and fun romance novel. The characters are charming, and the story provides plenty of laughter and warmth.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 49,
            'bookID' => 30,
            'rating' => 4,
            'comment' => 'An action-packed and thrilling ride. The plot is fast-paced, and the stakes are high, making it a page-turner from start to finish.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 40,
            'bookID' => 22,
            'rating' => 5,
            'comment' => 'A beautifully crafted fantasy adventure with a lot of heart. The world-building and characters make it a standout in the genre.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 31,
            'bookID' => 8,
            'rating' => 5,
            'comment' => 'A brilliant work of fantasy that blends adventure, politics, and magic. The world-building is rich, and the characters are complex.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 28,
            'bookID' => 45,
            'rating' => 4,
            'comment' => 'A mesmerizing story of a young woman’s journey through a magical world. The writing is beautiful, and the plot is full of twists.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 33,
            'bookID' => 29,
            'rating' => 4,
            'comment' => 'A thrilling science fiction novel that explores the possibilities of time travel. The concepts are mind-bending, and the story is captivating.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 22,
            'bookID' => 39,
            'rating' => 4,
            'comment' => 'A witty and thought-provoking novel about the absurdity of life. The characters are flawed but lovable, and the humor is dark and sharp.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 11,
            'bookID' => 19,
            'rating' => 5,
            'comment' => 'A poignant and heart-wrenching story about the human condition. It tackles deep themes with empathy and insight.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 16,
            'bookID' => 6,
            'rating' => 4,
            'comment' => 'An interesting and engaging historical fiction novel. The characters feel authentic, and the plot moves at a steady pace.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 47,
            'bookID' => 2,
            'rating' => 5,
            'comment' => 'A classic dystopian novel that explores the dangers of totalitarianism. The themes are still relevant today, making it a must-read.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 52,
            'bookID' => 21,
            'rating' => 4,
            'comment' => 'A beautifully crafted piece of literary fiction. The author’s prose is lyrical, and the story is filled with emotion and depth.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 56,
            'bookID' => 49,
            'rating' => 4,
            'comment' => 'A gripping and intense psychological thriller. The suspense builds steadily, and the twists and turns are genuinely shocking.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 55,
            'bookID' => 4,
            'rating' => 4,
            'comment' => 'A fast-paced action novel with plenty of intrigue and suspense. The plot is engaging, and the characters are memorable.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 51,
            'bookID' => 12,
            'rating' => 4,
            'comment' => 'A fun and quirky novel that provides plenty of laughs while still delivering a heartfelt story. A delightful read!',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 42,
            'bookID' => 26,
            'rating' => 5,
            'comment' => 'A stunning and emotional narrative about love, loss, and personal growth. The writing is raw and beautiful, and the characters are unforgettable.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 43,
            'bookID' => 18,
            'rating' => 4,
            'comment' => 'A chilling and atmospheric horror novel. The tension builds gradually, and the sense of dread is palpable throughout the story.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 49,
            'bookID' => 32,
            'rating' => 5,
            'comment' => 'A powerful novel about resilience and survival. The characters’ journey is both heartbreaking and inspiring, making it a must-read.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 39,
            'bookID' => 10,
            'rating' => 4,
            'comment' => 'A smart and witty political satire that takes aim at contemporary society. The humor is sharp, and the themes are deeply relevant.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 29,
            'bookID' => 48,
            'rating' => 4,
            'comment' => 'A suspenseful and thought-provoking story that explores complex ethical dilemmas. The writing is engaging, and the plot keeps you thinking long after finishing.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 19,
            'bookID' => 23,
            'rating' => 5,
            'comment' => 'A beautifully written novel about the beauty of human connections. The characters are rich and the emotional depth of the story is incredible.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 38,
            'bookID' => 33,
            'rating' => 4,
            'comment' => 'A captivating fantasy novel with an interesting magic system and a complex world. The characters are well-developed, and the story is full of surprises.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 17,
            'bookID' => 27,
            'rating' => 5,
            'comment' => 'A deep and thoughtful story that explores the intricacies of love, loss, and personal growth. The writing is delicate, and the themes are timeless.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 27,
            'bookID' => 43,
            'rating' => 4,
            'comment' => 'A fun and action-packed story with a likable protagonist. The pacing is quick, and the plot is full of twists that keep you engaged.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 37,
            'bookID' => 5,
            'rating' => 2,
            'comment' => 'The story drags on for far too long and lacks any real excitement. I couldn\'t connect with the characters, and the plot was predictable.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 47,
            'bookID' => 22,
            'rating' => 1,
            'comment' => 'Disappointing. The writing was dull, and the story didn\'t live up to the hype. I found myself skimming through most of it.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 36,
            'bookID' => 14,
            'rating' => 2,
            'comment' => 'The characters felt one-dimensional, and the plot was incredibly slow. I couldn\'t bring myself to care about what happened next.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 35,
            'bookID' => 30,
            'rating' => 1,
            'comment' => 'A complete letdown. The world-building was weak, and I didn\'t find the main character compelling at all. Not worth the read.',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'userID' => 25,
            'bookID' => 11,
            'rating' => 1,
            'comment' => 'I couldn\'t get into the story at all. It felt like it was trying too hard to be deep but just ended up boring me. The pacing was awful.',
            'created_at' => now(),
            'updated_at' => now(),
        ]        
    ]);
}

}
