<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'name' => 'admin',
                'email' => 'admin@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$9Px6.ogqxFPrOBAT/iEnzuhEtTZqhkgUx2ftzUO2k1rH5aHnSb4oW',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'The Ugly King',
                'email' => 'uglyking@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$dWjuwg5Fg4Ko2hQPVYvHfe3l8lbUzPubfZ/CwmTz2NYR95gmrf32e',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Silent Shadow',
                'email' => 'silentshadow@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$n52RXm6JP4d4WLMqfv7eUeU6JZejnfLaCPoohYxyw0LwGWrTvbzYK',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lost Pirate',
                'email' => 'lostpirate@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$gPj/Gtdr1j2prxbVgIVcEeOUAdbGpiU/ygw2EI4RMg0bZEqKZ58c.',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'BlueSky',
                'email' => 'bluesky@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$HxwOq86ZKjnAMSmakoDxIO8L.KvAmtD0z0m4b1PK.1/WI5IcsZwgy',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RedApple',
                'email' => 'redapple@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$tdcZdxi/yk6.gkCFPtUBPuis9D73hauTWVRqa8qjI.vsofKI59lTm',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GreenLeaf',
                'email' => 'greenleaf@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$IyhF72NiImEZsfRoCRWnbeLEc9NowqmZubFPZwMfZlLFQNucrvWfK',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HappyDay',
                'email' => 'happyday@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$RPlX/hwX947nEUGPSVUyCeFNihtF9fHQHaXe8D1HlKbdAsKrQXsxO',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'QuietStar',
                'email' => 'quietstar@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$X/RICkrR8n7nCj3HcER9hOhrPiYBS92G8ZzlyBe78ikwHkic918aO',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'BrightSun',
                'email' => 'brightsun@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$Sqg.hbDGtNcx0dV/dnCX6O09tSD7yEuEmjVAtah/AXRFWvQwpF/Mi',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SoftCloud',
                'email' => 'softcloud@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$mkmdiGi17CblX5BFq5XGO.S0UwJvWYAh68azPd3LoHkz9grw7ThEC',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SilverMoon',
                'email' => 'silvermoon@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$EbHz5qduwZDRqtz0WvjVuO5EyUPnMGcViUve5U0vhZ2LECqDaYb3q',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'QuickFox',
                'email' => 'quickfox@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$zU.mnsG.s6ldEKI9qnPy6.NVzJdBD6WCZfyioe4/v3tCYVYOI.k1W',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LazyBear',
                'email' => 'lazybear@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$l6XxdTVAlwvjQfJEYAmez.t7GGX0O0Ah7Tf3bbG2VvVzlmFMnI7yG',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'BlueWave',
                'email' => 'bluewave@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$W48kgDOhYJ4aDkOzIf4Rc.4RztGueYKYLqncFKcIjGut1.ANBMD7K',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CalmLake',
                'email' => 'calmlake@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$8g/B7QXwJwxiFEqHzEBU9.MHh20mMf3RkOblK8OhffgFanjvoKkCu',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GentleRain',
                'email' => 'gentlerain@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$zRkOsHdD4QJDE1CTgTOdcuY52C.uO/1zl3/XgypcU9ugSJTyhUaRi',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MistySky',
                'email' => 'mistysky@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$8hGVl2HLSPUU1hEqKiNZ3eY0Gf.85QpTIQywn9zDiLU0lFVmdcLfW',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SunnyMeadow',
                'email' => 'sunnymeadow@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$CZaBXgwmRkT2H5ruqmX6TeU7DnUQkuPUVSLHN.sV5orRxvHx0jSN2',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'DarkStone',
                'email' => 'darkstone@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$JNjXXqWdgOgrETMufoxyg.srD/eBsLnqgX5.i91.XIKdwzc1.lVne',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LightRiver',
                'email' => 'lightriver@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$KcTUi3fdE.w.BdPrdTDQoOWzHMhYjETXOlFt9siuk1DWEoKoR23b.',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'FreshWind',
                'email' => 'freshwind@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$yQ2HbjqmwQ6XVwEz6iS.dOATpinSbVWT/Vzsmvw7/AOwcqb2Y7fGe',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RedRose',
                'email' => 'redrose@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$scJthy/FnasUAA1azeJ05OL4K6sewHL2HY2F0F76lfEGYBmnICW8K',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GoldenLeaf',
                'email' => 'goldenleaf@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$xZYr.d6MOysR9OAvKNyX8.6ZXCwtkIokkQae7B0q4z/IZpu7CxXb6',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SilentBird',
                'email' => 'silentbird@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$OvDN9YiatqWjFREMh5oSb.xUgmllVjgi4VUR2CDke5.OctF.d7BWG',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SoftEcho',
                'email' => 'softecho@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$VExjfp4YAJdKEKnG/cQ0j.L8SnsIq4us1MQyQjvr/kDAkKnm4lm.S',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ClearWater',
                'email' => 'clearwater@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$FMZcktK6vQMOiTckeRJ7Nu9OruKbooYac8/3FRyOQAtqyVIsJVFC6',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'BrightStar',
                'email' => 'brightstar@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$NY/aVgCzdi4a1gxKXrtdBuCzw9R.7QnTwpNPAIZCoUqi.QNG5X6ou',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'QuietMoon',
                'email' => 'quietmoon@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$shsM8S.OM9sGWW/3DWZwY.wf5rx7ULrMtWejXj1CKxfbQTwQDw4XO',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SmallAnt',
                'email' => 'smallant@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$3EJnmWQfn15gLIWcMPUegeMJ6h5ncrF3hEzjgEjKxPwLwi2Dnzq9.',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'WiseOwl',
                'email' => 'wiseowl@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$ZBCm4LpZQPT6UJ3nyjzeou60pZ59UFd8/MwcwJCORj.UIG/mmBPTy',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TinyPebble',
                'email' => 'tinypebble@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$khUGGLupyZMIYjdjYg8UVuUT944FHi8JpDe6qYZvtRqMX09a3oNby',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'OldTree',
                'email' => 'oldtree@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$zbe2CrJf0TWyRkfDrIKEsO.vqNTWTijvfJ8RFwoV3iQnhupxZDiP6',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SilentWolf',
                'email' => 'silentwolf@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$mupRuqlc09O6J0EYe/J30eUYC9pCkpkV7XRKkkyZCfEqWaxG5pK7m',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'WarmFire',
                'email' => 'warmfire@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$ZZg20XVKi97ArKOw.5u.6.gWcUFSciW.5uhDBN3lEit3FMBJgcUVG',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SweetMelody',
                'email' => 'sweetmelody@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$cHWKa0LQ5b4H08JKaJ0tgewFjtSNRSA5.yZ14tQp02cAA7oshS8iW',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'OceanBreeze',
                'email' => 'oceanbreeze@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$wBar5hJtwqdjepVvgtlXlep6aant1mvAVwjC4x0kuznLvUTgNV41G',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LittleCloud',
                'email' => 'littlecloud@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$OYVws7qsi4ZvQ9k3UcNkR.aKBkitarQQhAG1GXyDeik.B4Y7t0r9S',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'FreshSpring',
                'email' => 'freshspring@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$vUZjtRnEY6UuSkxgmTctaOg1gCV06Hi2AA4z4p4dwndpt1eC3ApT.',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'BrightStarry',
                'email' => 'brightstarry@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$SLYXmFJFoT7dqgGU3srVTe42RnmlFQxpvaDYH0Hoivdj/DIcPdXDG',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SweetBerry',
                'email' => 'sweetberry@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$k88cpQ7tAPj0GkqtpkQR0umbllmRPwnZXNoqYTrigG/gmOY4hJt9W',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'FrostLeaf',
                'email' => 'frostleaf@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$.1fCmy.X1obOqa7BDNKYrOqwKsTd8SPeLsgEaLGlRfk/vzEkQkzWK',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CrystalWave',
                'email' => 'crystalwave@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$qmueHRQ3NRHq4464PPiJRuqEsZB3jwi6vYcUKgaxNTb/nRYhNIuYq',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'QuietRiver',
                'email' => 'quietriver@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$uuT34I/yTSjC0XfIfMGl3utsBw.aDDQ1By5fFWZcu754Zp8dEgdAi',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GoldenSun',
                'email' => 'goldensun@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$H7NyqfWi8l3NoThEcDtwNe8ut1rjfwvFJUA5I3A.pi5LnJPs60OzK',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LittleFlame',
                'email' => 'littleflame@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$4NLRuDsz55d61Cdwp2F6NeLjI26fk28apiK0AwCZDP6ueG36MdgYO',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ClearSky',
                'email' => 'clearsky@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$H7qf/hG/ek4IooIGgU50W.uiVgBYJqIi5RG0YlIQH9/Wt8c7o2xii',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SoftStone',
                'email' => 'softstone@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$5DbwtbooVrFCPfBBwE.MrOzhvBSLnUZTuinVBZu/WSXyP18O7LpxC',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SweetCloud',
                'email' => 'sweetcloud@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$lYddlrb1FCYlwOrjeAf4NujPBSCWzSDeMFch0dq3PR7oaWr0lQaKS',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GentleWave',
                'email' => 'gentlewave@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$N2Eg6u4n.uwsRpkYc5L.yu7QNi4OWUg9LEkD/woaLGwy0k9gz5OK6',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'CalmSea',
                'email' => 'calmsea@example.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$DL5a20a34l2NSTv.k7YexOpTPaBL43eF.6gUXabKT32rebaU7ymkO',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laiza Mae Barias',
                'email' => 'laizabarias@gmail.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$fFZ9lqFa00rjLUDPl2qV8usCqxYDbfaTpC/oJnwcAsCBy0Np2S/x2',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jeanliza Barias',
                'email' => 'jean@gmail.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$92v7xLTUtFw3k1wZ1bMZC.EoacDJynBsjefcL/nrfaYLpwKh50yVW',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'John Doe',
                'email' => 'johndoe@gmail.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$rM9inDZe8CvbibWZm/WzoeSDS9kjRFTeqDuk41CyWmCSHL5oKMp0G',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gold Ace',
                'email' => 'ace@gmail.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$2RO/xWl9pgvCoehKai8NC.Yc7UsNT9n2C6CAvCXvxMl3rrOMZYQ4K',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jo Jo',
                'email' => 'jojo@gmail.com',
                'email_verified_at' => now(),
                'password' => '$2y$12$TmzLgQooKna6nxJve/HWpOQF0ixHCPOsJQyIUUYVXZwWavdECmsm.',
                'remember_token' => NULL,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
